import type { InitialPresetString, JKFHand, JKFState } from "@/entities/kifu";

const EMPTY_HANDS: JKFHand = {
  FU: 0,
  KY: 0,
  KE: 0,
  GI: 0,
  KI: 0,
  KA: 0,
  HI: 0,
};

// === 平手の初期局面 ===
const HIRATE_STATE: JKFState = {
  color: 0, // 先手番
  board: [
    [
      { color: 1, kind: "KY" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "OU" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "KY" },
    ],
    [
      {},
      { color: 1, kind: "HI" },
      {},
      {},
      {},
      {},
      {},
      { color: 1, kind: "KA" },
      {},
    ],
    [
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
    ],
    [
      {},
      { color: 0, kind: "KA" },
      {},
      {},
      {},
      {},
      {},
      { color: 0, kind: "HI" },
      {},
    ],
    [
      { color: 0, kind: "KY" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "OU" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "KY" },
    ],
  ],
  hands: [EMPTY_HANDS, EMPTY_HANDS],
};

// === 香落ち（左香落ち）の初期局面 ===
const KY_STATE: JKFState = {
  color: 0,
  board: [
    [
      {},
      { color: 1, kind: "KE" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "OU" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "KY" },
    ],
    [
      {},
      { color: 1, kind: "HI" },
      {},
      {},
      {},
      {},
      {},
      { color: 1, kind: "KA" },
      {},
    ],
    [
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
    ],
    [
      {},
      { color: 0, kind: "KA" },
      {},
      {},
      {},
      {},
      {},
      { color: 0, kind: "HI" },
      {},
    ],
    [
      { color: 0, kind: "KY" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "OU" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "KY" },
    ],
  ],
  hands: [EMPTY_HANDS, EMPTY_HANDS],
};

// === 右香落ちの初期局面 ===
const KY_R_STATE: JKFState = {
  color: 0,
  board: [
    [
      { color: 1, kind: "KY" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "OU" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KE" },
      {},
    ],
    [
      {},
      { color: 1, kind: "HI" },
      {},
      {},
      {},
      {},
      {},
      { color: 1, kind: "KA" },
      {},
    ],
    [
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
    ],
    [
      {},
      { color: 0, kind: "KA" },
      {},
      {},
      {},
      {},
      {},
      { color: 0, kind: "HI" },
      {},
    ],
    [
      { color: 0, kind: "KY" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "OU" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "KY" },
    ],
  ],
  hands: [EMPTY_HANDS, EMPTY_HANDS],
};

// === 角落ちの初期局面 ===
const KA_STATE: JKFState = {
  color: 0,
  board: [
    [
      { color: 1, kind: "KY" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "OU" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "KY" },
    ],
    [{}, { color: 1, kind: "HI" }, {}, {}, {}, {}, {}, {}, {}], // 角なし
    [
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
    ],
    [
      {},
      { color: 0, kind: "KA" },
      {},
      {},
      {},
      {},
      {},
      { color: 0, kind: "HI" },
      {},
    ],
    [
      { color: 0, kind: "KY" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "OU" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "KY" },
    ],
  ],
  hands: [EMPTY_HANDS, EMPTY_HANDS],
};

// === 飛車落ちの初期局面 ===
const HI_STATE: JKFState = {
  color: 0,
  board: [
    [
      { color: 1, kind: "KY" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "OU" },
      { color: 1, kind: "KI" },
      { color: 1, kind: "GI" },
      { color: 1, kind: "KE" },
      { color: 1, kind: "KY" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, { color: 1, kind: "KA" }, {}], // 飛車なし
    [
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
      { color: 1, kind: "FU" },
    ],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [{}, {}, {}, {}, {}, {}, {}, {}, {}],
    [
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
      { color: 0, kind: "FU" },
    ],
    [
      {},
      { color: 0, kind: "KA" },
      {},
      {},
      {},
      {},
      {},
      { color: 0, kind: "HI" },
      {},
    ],
    [
      { color: 0, kind: "KY" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "OU" },
      { color: 0, kind: "KI" },
      { color: 0, kind: "GI" },
      { color: 0, kind: "KE" },
      { color: 0, kind: "KY" },
    ],
  ],
  hands: [EMPTY_HANDS, EMPTY_HANDS],
};

// === 初期局面マップ ===
export const INITIAL_STATES: Record<InitialPresetString, JKFState | null> = {
  HIRATE: HIRATE_STATE,
  KY: KY_STATE,
  KY_R: KY_R_STATE,
  KA: KA_STATE,
  HI: HI_STATE,
  HIKY: null, // 未実装
  "2": null, // 未実装
  "3": null, // 未実装
  "4": null, // 未実装
  "5": null, // 未実装
  "5_L": null, // 未実装
  "6": null, // 未実装
  "8": null, // 未実装
  "10": null, // 未実装
  OTHER: null, // dataフィールドを使用
};
